### ISSUE TITLE
Test certificate for DTLS Server

### ISSUE THREAD

**Issue by roubra** [Infineon/optiga-trust-m#1]
Hi,
we are currently trying to implement a DTLS implementation for the Optiga Trust M. For this we would need a key pair for the server (OpenSSL). We would like to create this with the test CA, but we don't have the private key. Is there a way to get it? At Optiga Trust X it was included in the "Starter pack".
Kind regards,
Rouven

**Comment by ayushev** [comment]
Files uploaded
