### ISSUE TITLE
Get a random number in a specified range

### ISSUE THREAD

**Issue by gernertd** [Infineon/optiga-trust-m#11]
Is it possibleto get a random number in a specified range?
For example a number between 1-6.

**Comment by pwiegele** [comment]
Hi gernertd,

sry for the late reply. You see the documentation of the our crypto API [here](https://github.com/Infineon/optiga-trust-m/wiki/Trust-M-Crypt-API#optiga_crypt_random).

In short you have to request at least 8 bytes of randomness. My recommendation would be to request 8bytes and strip the rest.
