### ISSUE TITLE
Optiga Trust M for STM32

### ISSUE THREAD

**Issue by ppradeepubi** [Infineon/optiga-trust-m#114]
Hi,

I am working of porting Optiga Trust M for STM32, I have got a few examples working looking at the solution provided for earlier issues. My queries are 

1. The TIMER_EVENT is for what duration, is it 1000 micro seconds ?, but in ESP32_freeRTOS code I see that its configures for 10ms. What does the optiga library expect ? 
2. What is the heap and stack size requirements for optiga library. I have to disable few tasks in my code to get the library working.

Thanks.

**Comment by koblibri** [comment]
Hi!

1.) Are you referring to the implementation of the function "pal_os_event_register_callback_oneshot"? If yes, this function should ideally be implemented in a way, that the given argument of "time_us" (a value in Microseconds) is passed on to the actual timer.

2.) For the code footprint and how to reduce it, please see here: https://github.com/Infineon/optiga-trust-m/wiki/Code-Footprint
