### ISSUE TITLE
Issues using Shielded connection

### ISSUE THREAD

**Issue by ppradeepubi** [Infineon/optiga-trust-m#119]
I have been able to port Optiga Library for STM32L4. I am able to read COUID successfully. But,  when I enable Shielded Connection. I get Failure for the COUID read.  Error 0x107 ( Presentation layer error). Can you please provide some suggestions on what could be wrong.

**Comment by ShaikKarishma0** [comment]
Hi @ppradeepubi,

Before using the Shielded Connection, please ensure that the OPTIGA Trust M and the Host are paired using a shared secret (this secret key is used for the secure communication). 
To share the secret, you have to execute the pair_host_and_optiga_using_pre_shared_secret() function. Please refer the existing example for details on this implementation - https://github.com/Infineon/optiga-trust-m/blob/develop/examples/optiga/usecases/example_pair_host_and_optiga_using_pre_shared_secret.c
