### ISSUE TITLE
Link for "OPTIGA™ Trust M Zephyr PAL & Application" on the main page is broken

### ISSUE THREAD

**Issue by farrellaultman** [Infineon/optiga-trust-m#124]
**Prerequisites**

Can you reproduce the problem reliably? y

Did you check current release notes for known issues? y

If this is not the latest release, have you checked newer releases? 

**Description**:

**Steps to Reproduce:**

1. Just click on the link for "OPTIGA™ Trust M Zephyr PAL & Application".

2. Page not found displayed

3.

**Expected Result:**
Zephyr example

**Actual Result:**
Page not found

**Frequency (1/1, 1/50, 1/100):**
1/1

**Build/Commit:**

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.

**Target:**

The chip or kit you are working with

**Host OS and Version:**

MacOS, Windows, Linux

**Compiler:**

Include the version!

**Environment**

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

**Comment by aoune-ayoub** [comment]
We are aware of the missing link, the zephyr PAL & application will be released on Github very soon.

**Comment by aoune-ayoub** [comment]
The zephyr application is now live and the link should send you to the repository where a zephyr application is present.

**Comment by farrellaultman** [comment]
Thanks!!
