### ISSUE TITLE
PAL: nRF5x

### ISSUE THREAD

**Issue by tejaChintalapatiPD** [Infineon/optiga-trust-m#33]
Hi @ayushev. Can you please tell me if there is an official PAL in works for nRF5x SoCs?

**Comment by ayushev** [comment]
Hi @tejaChintalapatiPD with minor changes the pal layer from the m1 can be used 1-1 https://github.com/Infineon/optiga-trust-m/tree/master/pal/nrf5x

**Comment by tejaChintalapatiPD** [comment]
Awesome!

My bad. I didn't check the master branch. Thanks for the help.
