### ISSUE TITLE
Open/close sequence

### ISSUE THREAD

**Issue by ayushev** [Infineon/optiga-trust-m#42]
Hello,
looks like I fixed it. The frame umber was missing in FCTR. I have another question though:

Should I close an application after every command?
Or which sequence is correct:

a) OpenApplication->GenKeyPair->CloseAppl->OpenAppl->EncryptAsym->CloseAppl
b) OpenAppl->GenKeyPair->EncryptAsym->CloseAppl

Regards

_Originally posted by @INfinnnnn in https://github.com/Infineon/optiga-trust-m/issues/41#issuecomment-766156184_

**Comment by ayushev** [comment]
Hi @INfinnnnn 

the sequence should be as follows:
Open application
Execute as many commands as you wish
Close application

**Comment by INfinnnnn** [comment]
ok thanks
