### ISSUE TITLE
Regarding contain of device cert. generated by Trust-M

### ISSUE THREAD

**Issue by toshi-onion** [Infineon/optiga-trust-m#48]
Hello Infineon's expert,
In using Infineon CA, is Infineon CA support OSCP?

**Comment by pwiegele** [comment]
Hello @toshi-onion,

can you please explain your use-case and how you want to use OCSP?

BR Paul

**Comment by pwiegele** [comment]
@toshi-onion can we close this one?

**Comment by sgsharath123** [comment]
Hi @toshi-onion

Please contact the local support for any custom orders as OCSP is not part of the standard OPTIGA package or delivery.

We are closing this issue as there is no feedback for few days now. Please re-open the issue or create another in case you need further info or support.
