### ISSUE TITLE
Reduce Code-Footprint

### ISSUE THREAD

**Issue by BonfiglC** [Infineon/optiga-trust-m#49]
Hi *,

In regards to the code footprint listed in Wiki:
https://github.com/Infineon/optiga-trust-m/wiki/Code-Footprint

I am interested in getting to know if "ECC; Protected Update; RND; TLS PRF", which is listed to require 5.2 kB of flash can be further stripped down or is this available as one single package only?

E.g. if I am interested in ECC only, can I leave out the remaining options "Protected Update; RND; TLS PRF"?

**Comment by ayushev** [comment]
Of course it can be stripped down.
To decrease you can use any of the following macros: https://github.com/Infineon/optiga-trust-m/blob/trust_m1_m3/optiga/include/optiga/optiga_lib_config_m_v3.h#L46-L97
Also below the code foorptint you can find further details on the code footprint reduction based on your needs
https://github.com/Infineon/optiga-trust-m/wiki/Code-Footprint#how-to-optimize

In any case, if you like to do you own calculation, you can open the getting started project, change configuration, enable Optiomization for size (-Os, for this right click on teh project, select properties-> C/C++ Build-> Settings-> Optimization), build the project and feed the resulting file into the amap tool suggested in the article.
Let me knwo if further support is needed.
