### ISSUE TITLE
Ho to use Trust M in Android 10

### ISSUE THREAD

**Issue by Emilnet** [Infineon/optiga-trust-m#69]
Hi Sir,

We want to use Trust M in Android 10 for IoT gateway application.
Does Infineon offer Trust M driver and example code for Android?
if no, please assist me how to do.

Thanks.

**Comment by pwiegele** [comment]
Hi @Emilnet,

[Here](https://github.com/Infineon/linux-optiga-trust-m) you can find our repository for Trust M usage under linux. From what I understand you can choose in Android which crypto provider you want to use. Have a look at the repository and the examples for openssl. 

HTH
