### ISSUE TITLE
Verify Trust M Signature with OpenSSL

### ISSUE THREAD

**Issue by ayushev** [Infineon/optiga-trust-m#73]
Thanks, I got what you answered cleared up and now I got another question. I have gotten both storage of keys, signing of digest, and verification of it to work great using the optiga chip. I however do not wanna rely on the optiga chip for verification of digest. I have therefore tried the inbuilt function of openssl **dgst**, but I cant get it to work. Do you have any clue what kind of conversion you have to do(if any) of public key, signature and digest from the pure hex format they are given in using the optiga sign function and generate_key function. That is to get them to work with the openssl dgst command. A programmatic approach not relying on the optiga chip is also very welcome if you have any. THe way I understand it the public key is encoded in ASN.1 format, and the signature is encoded in just pure HEX-format?

_Originally posted by @KjetilSekse in https://github.com/Infineon/optiga-trust-m/issues/70#issuecomment-940740504_

**Comment by ayushev** [comment]
> Find the answer where? I think you forgot to link something or add the relevant information? Thanks in advance 

Thanks for pointing. Fixed now.

**Comment by KjetilSekse** [comment]
I see you say that I should prepend the header to the SIGNATURE in your answer, but in the original post you answered you told the guy to prepend it to his public key to make it accepted by third party tools. Do I need to prepend the header to BOTH public key and signature or ONLY signature if I want to make it compatible with the [openssl-dgst ](https://www.openssl.org/docs/man1.0.2/man1/openssl-dgst.html)command?

**Comment by KjetilSekse** [comment]
YEs, it works great now. Thanks for the help once again!

man. 18. okt. 2021 kl. 22:19 skrev Artem Yushev ***@***.***>:
