### ISSUE TITLE
Modification of metadata in optiga certificate slot 0xE0E0

### ISSUE THREAD

**Issue by KjetilSekse** [Infineon/optiga-trust-m#75]
Hello, It says in the reference manual that Public key certificate 1 (0xE0E0) which is issued by infineon usually can be **reused to provision customer specific certificate**. I however am not able to change the metadata of the object to be able to write to it. The metadata I have used can be seen below. Do you have any suggestions to change the metadata, or how do I go forward if I want to override the data in the object with a self chosen public key/certificate? 

const uint8_t metadata_customer_certificate[]=  {0x20, 0x0B, // Length of metadata excluding this line in elements (0x09)
    0xc0, 0x01, 0x01, //  State of the register is creation 
     0xE1 , 0x01, 0x30, // set key container access as read in creation and init
     0xD0, 0x01, 0x00,   // Always allow to change this register: WRITE = ALW
     0xD1, 0x01, 0x00, // Always allow to read from this register: READ = ALW
     };

**Comment by sgsharath123** [comment]
Hi @KjetilSekse 

Do you have a feedback on the above hints provided? Did it work? Could we close this issue?

**Comment by KjetilSekse** [comment]
Yes you can close

man. 29. nov. 2021 kl. 11:15 skrev Sharath Venkatesh <
***@***.***>:
