### ISSUE TITLE
Linux is not compiling on latest version

### ISSUE THREAD

**Issue by Fassino** [Infineon/optiga-trust-m#84]
Hi all,

Linux is not compiling with latest revision where some ordre in a enum has been changed in definition and not in linux.

Could you fix it ?

/home/jp/mbedtls-2.28/trustm/optiga-trust-m/pal/linux/target/ultra96/pal_ifx_i2c_config.c:44:1: warning: missing initializer for field ‘upper_layer_event_handler’ of ‘pal_linux_t’ {aka ‘struct pal_linux’} [-Wmissing-field-initializers]
 pal_linux_t linux_events = {"/dev/i2c-1", 0};
 ^~~~~~~~~~~
In file included from /home/jp/mbedtls-2.28/trustm/optiga-trust-m/pal/linux/target/ultra96/pal_ifx_i2c_config.c:42:
/home/jp/mbedtls-2.28/trustm/optiga-trust-m/pal/linux/pal_linux.h:57:12: note: ‘upper_layer_event_handler’ declared here
     void * upper_layer_event_handler;
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/jp/mbedtls-2.28/trustm/optiga-trust-m/pal/linux/target/ultra96/pal_ifx_i2c_config.c:58:5: error: initialization of ‘void *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
     0x30,
     ^~~~
/home/jp/mbedtls-2.28/trustm/optiga-trust-m/pal/linux/target/ultra96/pal_ifx_i2c_config.c:58:5: note: (near initialization for ‘optiga_pal_i2c_context_0.p_upper_layer_ctx’)
/home/jp/mbedtls-2.28/trustm/optiga-trust-m/pal/linux/target/ultra96/pal_ifx_i2c_config.c:62:5: error: initialization of ‘unsigned char’ from ‘void *’ makes integer from pointer without a cast [-Werror=int-conversion]
     NULL
     ^~~~
/home/jp/mbedtls-2.28/trustm/optiga-trust-m/pal/linux/target/ultra96/pal_ifx_i2c_config.c:62:5: note: (near initialization for ‘optiga_pal_i2c_context_0.slave_address’)
cc1: all warnings being treated as errors
make[2]: *** [library/hw/trustm/CMakeFiles/trustm.dir/build.make:297: library/hw/trustm/CMakeFiles/trustm.dir/__/__/__/trustm/optiga-trust-m/pal/linux/target/ultra96/pal_ifx_i2c_config.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:465: library/hw/trustm/CMakeFiles/trustm.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Best regards
JP Fassino

**Comment by ying-css** [comment]
@Fassino   Which Linux version are you using currently? with the latest  optiga-trust-m library?  Thanks

**Comment by Fassino** [comment]
I'm using Ubuntu 64-bits cross compiling using gcc for embedded Linux on the latest optiga-trust-m library.

**Comment by ying-css** [comment]
@Fassino Which gcc version are you using? We just compiled successfully with the latest optiga-trust-m library by using gcc 10.2.1. Thanks.

**Comment by Fassino** [comment]
gcc version 8.3.0 (Linaro GCC 8.2-2018.08~dev)  with many mlany warning as error.

The issue come here.

 In pal/linux/target/ultra96/pal_ifx_i2c_config.c:

pal_i2c_t optiga_pal_i2c_context_0 =
{
    /// Pointer to I2C master platform specific context
    (void*)&linux_events,
    /// Slave address
    0x30,
    /// Upper layer context
    NULL,
    /// Callback event handler
    NULL
};

While in header file optiga/include/optiga/pal/pal_i2c.h:


/** @brief PAL I2C context structure */
typedef struct pal_i2c
{
    /// Pointer to I2C master platform specific context
    void * p_i2c_hw_config;
    /// Pointer to store the callers context information
    void * p_upper_layer_ctx;
    /// Pointer to store the callers handler
    void * upper_layer_event_handler;
    /// I2C slave address
    uint8_t slave_address;
} pal_i2c_t;

It comes from the move of slave_address in the structure definition in last commits.

**Comment by Fassino** [comment]
Hi All,

Any news ?

Thanks

**Comment by sgsharath123** [comment]
Hello @Fassino 
Could you please provide link to the latest commit you're talking about?
In the "develop" branch of this repository, both the c and h files have similar structure defined (in c) and declared (in h).

**Comment by Fassino** [comment]
Hello @sgsharath123 ,

Je latest one: commit 3b2a33c112d531ee15bae143d8716cbfcaf9957c

**Comment by sgsharath123** [comment]
Hello @Fassino , thanks for the details, we will get back to you after checking this internally.

**Comment by ying-css** [comment]
Hello @Fassino, we are looking into all the compilation options you are using and will update the pal layer for Linux very soon. Thanks.

**Comment by RaymWong** [comment]
Fixed in the following commit with updated Optiga host library: 
[https://github.com/Infineon/linux-optiga-trust-m/commit/398a7a0d255f2d7e4d28e05d7bf8102c710eb0c5](url)
