### ISSUE TITLE
Efficient ECDSA library for Aurix TC2x

### ISSUE THREAD

**Issue by arne123** [Infineon/optiga-trust-m#87]
We are intending to verify a ECDSA Signature generated with an Optiga-trust-m on the AURIX TC2x
Is there an efficient ECDSA implementation, in best case without dynamic memory allocation, known or available for the TC2xx Controller Series?

**Comment by sgsharath123** [comment]
Hello @arne123 ,
I believe you are using Aurix TC2x for automotive and hence you prefer no dynamic allocation.
We do not have ECDSA implementation on Aurix, it has to be implemented on your side.
One hint from us is to try using openssl implementation of ECDSA for development purposes (use at your own risk as this may not be qualified enough for automotive use cases).
